"""add database constraints and indexes

Revision ID: 105775547ba6
Revises: 150f6cfc7026
Create Date: 2026-10-07 08:21:19.812173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105775547ba6'
down_revision: Union[str, Sequence[str], None] = '150f6cfc7026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_availabilities_participant_id'), 'availabilities', ['participant_id'], unique=False)
    op.create_index(op.f('ix_meetings_organization_id'), 'meetings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meetings_organizer_id'), 'meetings', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_participants_meeting_id'), 'participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    op.create_unique_constraint('uq_participant_user_meeting', 'participants', ['user_id', 'meeting_id'])
    op.create_index(op.f('ix_scheduling_requests_created_by'), 'scheduling_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_scheduling_requests_meeting_id'), 'scheduling_requests', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_scheduling_requests_meeting_id'), table_name='scheduling_requests')
    op.drop_index(op.f('ix_scheduling_requests_created_by'), table_name='scheduling_requests')
    op.drop_constraint('uq_participant_user_meeting', 'participants', type_='unique')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_meeting_id'), table_name='participants')
    op.drop_index(op.f('ix_meetings_organizer_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organization_id'), table_name='meetings')
    op.drop_index(op.f('ix_availabilities_participant_id'), table_name='availabilities')
    # ### end Alembic commands ###
