"""add duration to scheduling requests

Revision ID: 883f8cea56ad
Revises: 3572fa8b77b1
Create Date: 2026-10-08 22:32:23.656154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883f8cea56ad'
down_revision: Union[str, Sequence[str], None] = '3572fa8b77b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduling_requests', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduling_requests', 'duration_minutes')
    # ### end Alembic commands ###
