"""add meeting scheduling fields

Revision ID: fe6a60961e08
Revises: 883f8cea56ad
Create Date: 2026-10-08 22:40:16.617191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a60961e08'
down_revision: Union[str, Sequence[str], None] = '883f8cea56ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('meetings', sa.Column('scheduled_start', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('scheduled_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'scheduled_end')
    op.drop_column('meetings', 'scheduled_start')
    op.drop_column('meetings', 'status')
    # ### end Alembic commands ###
